In [1]:
import pandas as pd
import matplotlib.pyplot as plt
print("Libraries loaded successfully")

Libraries loaded successfully

In [63]:
df = pd.read_csv('/home/abhishek/projects/python_prep/data/sales_data_sample.csv',
                 parse_dates=['ORDERDATE'])

# df.info()
df.tail(3)
# df.describe()
# df.shape
# df.dtypes
# df.columns.tolist()
# df.duplicated().sum()
# df[['ORDERNUMBER','QUANTITYORDERED','PRICEEACH','SALES','ORDERDATE','STATUS']].head(3)
# df[(df['SALES'] > 5000) & (df['STATUS'] == 'Disputed') | (df['STATUS'] == 'Shipped')][['ORDERNUMBER','QUANTITYORDERED','PRICEEACH','SALES','ORDERDATE','STATUS']].head(20)
df.query(" SALES > 8000 and STATUS == 'Disputed'")[['ORDERNUMBER','QUANTITYORDERED','PRICEEACH','SALES','ORDERDATE','STATUS']].head(2)

     ORDERNUMBER  QUANTITYORDERED  PRICEEACH    SALES  ORDERDATE    STATUS
105        10417               56      100.0  9218.16 2005-05-13  Disputed
473        10406               61      100.0  8374.69 2005-04-15  Disputed

In [145]:
# df.info()
# df.loc[0,['ORDERNUMBER','QUANTITYORDERED','PRICEEACH','SALES','ORDERDATE','STATUS']]
# df.iloc[0:10,[0,1,2,3,4]]
# df = pd.read_csv('/home/abhishek/projects/python_prep/data/sales_data_sample.csv',
#                  parse_dates=['ORDERDATE'])
# df[((df['ORDERNUMBER'] == 10121) & (df['ORDERDATE'] == pd.to_datetime('5/7/2003'))) | 
#    (df['ORDERNUMBER'] == 10107) & (df['ORDERDATE'] == pd.to_datetime('2/24/2003'))].iloc[0:10,[0,1,2,4,5,6]]
# df[(df['ORDERNUMBER'].isin([10121, 10107])) & (df['SALES'].isna())].iloc[0:10,[0,1,2,4,5,6]]

# newdf1 = df.loc[:9,[['STATUS','PRODUCTLINE']]]
newdf = df.loc[df['ORDERNUMBER'].isin([10121, 10107]) , df.columns[[0,1,2,4,5,6]]
].head(10).fillna(0.0)

newdf['TAX'] = newdf['SALES'] * 0.05
newdf['STATUS'] = newdf['STATUS'].apply(lambda x: x.upper())
newdf['MORE_TAX'] = newdf['TAX'] > 150
newdf['TOTALAMOUNT'] = newdf['SALES'] + newdf['TAX']
df1 = df.loc[:9,['STATUS','PRODUCTLINE']]
df1['NEWCOL'] = df1['STATUS'] + ' - ' + df1['PRODUCTLINE']
# df.loc[:9,['STATUS','PRODUCTLINE']]
newdf['SALETYPE'] = newdf['SALES'].apply(lambda x: 'HIGH' if x > 5000 else 'LOW').head(20)
newdf
# df.query("ORDERNUMBER in [10107,10121] and SALES.isnull()").iloc[:20,[0,1,2,4,5,6]]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,SALES,ORDERDATE,STATUS,TAX,MORE_TAX,TOTALAMOUNT,SALETYPE
0,10107,30,95.70,2871.00,2003-02-24,SHIPPED,143.5500,False,3014.5500,LOW
1,10121,34,81.35,2765.90,2003-05-07,SHIPPED,138.2950,False,2904.1950,LOW
2,10107,30,95.70,0.00,2003-02-24,SHIPPED,0.0000,False,0.0000,LOW
3,10121,34,81.35,0.00,2003-05-07,SHIPPED,0.0000,False,0.0000,LOW
56,10107,39,99.91,3896.49,2003-02-24,SHIPPED,194.8245,True,4091.3145,LOW
82,10107,27,100.00,6065.55,2003-02-24,SHIPPED,303.2775,True,6368.8275,HIGH
242,10107,21,100.00,3036.60,2003-02-24,SHIPPED,151.8300,True,3188.4300,LOW
243,10121,50,100.00,8284.00,2003-05-07,SHIPPED,414.2000,True,8698.2000,HIGH
806,10107,29,70.87,2055.23,2003-02-24,SHIPPED,102.7615,False,2157.9915,LOW
1468,10107,25,100.00,2845.75,2003-02-24,SHIPPED,142.2875,False,2988.0375,LOW